const types = {
    LIST_ALL: '@app/LIST_ALL',
    UPDATE_APP: '@app/UPDATE_APP',
    SAVE_MOVIMENTACAO: '@app/SAVE_MOVIMENTACAO',
    FETCH_CADASTRO: '@app/FETCH_CADASTRO',
    SAVE_MATERIAL: '@app/SAVE_MATERIAL',
    SAVE_LAUDO: '@app/SAVE_LAUDO',
    SAVE_LOTE: '@app/SAVE_LOTE',
    SAVE_CA: '@app/SAVE_CA',
    SAVE_NOTA: '@app/SAVE_NOTA',
    SAVE_CENTRO: '@app/SAVE_CENTRO',
    SAVE_FORNECEDOR: '@app/SAVE_FORNECEDOR',
    SAVE_COLABORADOR: '@app/SAVE_COLABORADOR',
    AUTORIZAR_MOVIMENTACAO: '@app/AUTORIZAR_MOVIMENTACAO',
    GET_MOVIMENTACAO: '@app/GET_MOVIMENTACAO',
    API_REQUEST: '@app/API_REQUEST',
    
    
};

export default types;